version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 5
    groups:
      cargo:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /npm
    schedule:
      interval: weekly
    target-branch: develop
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: develop
    groups:
      actions:
        patterns: ["*"]
